server:
  port: 8084

spring:
  application:
    name: function-service

  rabbitmq:
    host: ${RABBITMQ_HOST:logistics-rabbitmq}
    port: 5672
    username: guest
    password: guest

  cloud:
    function:
      # matches the method name in WaybillFunction.java
      definition: generateWaybill
    stream:
      bindings:
        generateWaybill-in-0:
          destination: shipment_exchange
          group: pdf-generators

    #stream:
      #bindings:
        # Syntax: <functionName>-in-<index>
        #generateWaybill-in-0:
          #destination: shipment_exchange # Ensure Producer sends to this Exchange
          #group: function_queue_group
          #content-type: application/json

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:logistics-registry}:8761/eureka/